language: csharp
solution: CS.Utils.sln

matrix:
  include:
    - dotnet: 2.1
      mono: none
      os: linux
    # - dotnet: 2.2
      # mono: none
      # os: linux
    - dotnet: 2.1.502
      mono: none
      os: osx
    - dotnet: 2.2.101
      mono: none
      os: osx
  
install:
  - dotnet restore
script:
  - dotnet build CS.Utils.sln
  - dotnet test CS.Utils.sln
